import { defineType, defineField } from "sanity";

export default defineType({
  name: "camp",
  title: "Camp",
  type: "document",
  groups: [
    { name: "overview", title: "Overview & Settings", default: true },
    { name: "surfPage", title: "Surf Page" },
    { name: "roomsPage", title: "Rooms Page" },
    { name: "foodPage", title: "Food Page" },
    { name: "seo", title: "SEO" },
  ],
  fields: [
    defineField({
      name: "language",
      type: "string",
      readOnly: true,
      hidden: true,
    }),
    defineField({
      name: "name",
      title: "Name",
      type: "string",
      validation: (r) => r.required(),
      group: "overview",
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "name", maxLength: 96 },
      validation: (r) => r.required(),
      group: "overview",
    }),
    defineField({
      name: "country",
      title: "Country",
      type: "reference",
      to: [{ type: "country" }],
      validation: (r) => r.required(),
      group: "overview",
    }),
    defineField({
      name: "location",
      title: "Location Label",
      type: "string",
      description: "e.g. 'Bukit Peninsula, Bali'",
      group: "overview",
    }),
    defineField({
      name: "tagline",
      title: "Tagline",
      type: "string",
      group: "overview",
    }),
    defineField({
      name: "image",
      title: "Card Image",
      type: "image",
      options: { hotspot: true },
      group: "overview",
    }),
    defineField({
      name: "heroImages",
      title: "Hero Images",
      type: "array",
      of: [{ type: "image", options: { hotspot: true } }],
      description: "Rotating hero background images. First image is shown initially.",
      group: "overview",
    }),
    defineField({
      name: "heroTitle",
      title: "Hero Title",
      type: "string",
      description:
        'Override the hero headline. Defaults to "Rapture Surf Camp {name}". Use \\n for line breaks.',
      group: "overview",
    }),
    defineField({
      name: "heroSubtitle",
      title: "Hero Subtitle",
      type: "string",
      description: "Optional text below the hero headline.",
      group: "overview",
    }),
    defineField({
      name: "heroTagline",
      title: "Hero Tagline",
      type: "string",
      description: "Optional small uppercase text above the hero headline.",
      group: "overview",
    }),
    defineField({
      name: "rating",
      title: "Rating",
      type: "number",
      validation: (r) => r.min(0).max(5).precision(1),
      group: "overview",
    }),
    defineField({
      name: "reviewCount",
      title: "Review Count",
      type: "number",
      group: "overview",
    }),
    defineField({
      name: "amenities",
      title: "Amenities",
      type: "array",
      of: [{ type: "string" }],
      options: { layout: "tags" },
      group: "overview",
    }),
    defineField({
      name: "bookingUrl",
      title: "Booking URL",
      type: "url",
      group: "overview",
    }),
    defineField({
      name: "latitude",
      title: "Latitude",
      type: "number",
      group: "overview",
    }),
    defineField({
      name: "longitude",
      title: "Longitude",
      type: "number",
      group: "overview",
    }),
    defineField({
      name: "elfsightId",
      title: "Elfsight App ID",
      type: "string",
      description: "Elfsight reviews widget App ID",
      group: "overview",
    }),
    defineField({
      name: "pageBuilder",
      title: "Overview Page Content",
      type: "array",
      of: [
        { type: "contentBlock" },
        { type: "imageGrid" },
        { type: "imageBreak" },
        { type: "imageCarousel" },
        { type: "imageGallery" },
        { type: "videoBlock" },
        { type: "videoTestimonials" },
        { type: "highlightsGrid" },
        { type: "inclusionsGrid" },
        { type: "faqSection" },
        { type: "ctaSection" },
      ],
      group: "overview",
    }),
    defineField({
      name: "surfHeroTitle",
      title: "Surf Hero Title",
      type: "string",
      description: 'Override the hero headline on the Surf page. Defaults to "Surf".',
      group: "surfPage",
    }),
    defineField({
      name: "surfPageBuilder",
      title: "Surf Page",
      type: "array",
      of: [
        { type: "surfIntro" },
        { type: "surfForecast" },
        { type: "surfSpots" },
        { type: "surfLevels" },
        { type: "surfSchedule" },
        { type: "surfEquipment" },
        { type: "contentBlock" },
        { type: "imageGrid" },
        { type: "imageBreak" },
        { type: "imageCarousel" },
        { type: "imageGallery" },
        { type: "videoBlock" },
        { type: "videoTestimonials" },
        { type: "highlightsGrid" },
        { type: "inclusionsGrid" },
        { type: "faqSection" },
        { type: "ctaSection" },
      ],
      group: "surfPage",
    }),
    defineField({
      name: "roomsHeroTitle",
      title: "Rooms Hero Title",
      type: "string",
      description: 'Override the hero headline on the Rooms page. Defaults to "Rooms".',
      group: "roomsPage",
    }),
    defineField({
      name: "roomsPageBuilder",
      title: "Rooms Page",
      type: "array",
      of: [
        { type: "roomTypes" },
        { type: "roomInclusions" },
        { type: "roomFacilities" },
        { type: "contentBlock" },
        { type: "imageGrid" },
        { type: "imageBreak" },
        { type: "imageCarousel" },
        { type: "imageGallery" },
        { type: "videoBlock" },
        { type: "videoTestimonials" },
        { type: "highlightsGrid" },
        { type: "inclusionsGrid" },
        { type: "faqSection" },
        { type: "ctaSection" },
      ],
      group: "roomsPage",
    }),
    defineField({
      name: "foodHeroTitle",
      title: "Food Hero Title",
      type: "string",
      description: 'Override the hero headline on the Food page. Defaults to "Food".',
      group: "foodPage",
    }),
    defineField({
      name: "foodPageBuilder",
      title: "Food Page",
      type: "array",
      of: [
        { type: "foodIntro" },
        { type: "mealCards" },
        { type: "menuTable" },
        { type: "dietaryOptions" },
        { type: "contentBlock" },
        { type: "imageGrid" },
        { type: "imageBreak" },
        { type: "imageCarousel" },
        { type: "imageGallery" },
        { type: "videoBlock" },
        { type: "videoTestimonials" },
        { type: "highlightsGrid" },
        { type: "inclusionsGrid" },
        { type: "faqSection" },
        { type: "ctaSection" },
      ],
      group: "foodPage",
    }),
    defineField({
      name: "seo",
      title: "SEO",
      type: "seo",
      group: "seo",
    }),
  ],
  preview: {
    select: {
      title: "name",
      subtitle: "country.name",
      media: "image",
    },
  },
});
