import { defineType, defineField } from "sanity";

export default defineType({
  name: "camp",
  title: "Camp",
  type: "document",
  groups: [
    { name: "overview", title: "Overview & Settings", default: true },
    { name: "seo", title: "SEO" },
  ],
  fieldsets: [
    {
      name: "introSection",
      title: "Intro Section",
      options: { collapsible: true, collapsed: true },
    },
  ],
  fields: [
    defineField({
      name: "language",
      type: "string",
      readOnly: true,
      hidden: true,
    }),
    defineField({
      name: "name",
      title: "Name",
      type: "string",
      validation: (r) => r.required(),
      group: "overview",
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: {
        source: "name",
        maxLength: 96,
        isUnique: async (value, context) => {
          const { document, getClient } = context;
          const client = getClient({ apiVersion: "2024-01-01" });
          const lang = (document as any)?.language || "en";
          const id = document?._id?.replace(/^drafts\./, "");
          const count = await client.fetch(
            `count(*[_type == "camp" && slug.current == $slug && (language == $lang || (!defined(language) && $lang == "en")) && !(_id in [$pubId, $draftId])])`,
            { slug: value, lang, pubId: id, draftId: `drafts.${id}` },
          );
          return count === 0;
        },
      },
      validation: (r) => r.required(),
      group: "overview",
    }),
    defineField({
      name: "country",
      title: "Country",
      type: "reference",
      to: [{ type: "country" }],
      validation: (r) => r.required(),
      group: "overview",
    }),
    defineField({
      name: "location",
      title: "Location Label",
      type: "string",
      description: "e.g. 'Bukit Peninsula, Bali'",
      group: "overview",
    }),
    defineField({
      name: "tagline",
      title: "Tagline",
      type: "string",
      group: "overview",
    }),
    defineField({
      name: "introText",
      title: "Intro Text",
      type: "text",
      rows: 6,
      description:
        "Description shown below the tagline on the overview page. Use a blank line to separate paragraphs.",
      group: "overview",
      fieldset: "introSection",
    }),
    defineField({
      name: "surfLevels",
      title: "Surf Levels",
      type: "string",
      description: 'e.g. "All Levels", "Intermediate+"',
      initialValue: "All Levels",
      group: "overview",
      fieldset: "introSection",
    }),
    defineField({
      name: "minStay",
      title: "Min. Stay",
      type: "string",
      description: 'e.g. "3 nights", "7 nights"',
      initialValue: "3 nights",
      group: "overview",
      fieldset: "introSection",
    }),
    defineField({
      name: "groupSize",
      title: "Group Size",
      type: "string",
      description: 'e.g. "Max 5:1 ratio", "Up to 35 guests"',
      initialValue: "Max 5:1 ratio",
      group: "overview",
      fieldset: "introSection",
    }),
    defineField({
      name: "spokenLanguages",
      title: "Languages",
      type: "string",
      description: 'e.g. "EN, DE, PT, ES"',
      initialValue: "EN, DE, PT, ES",
      group: "overview",
      fieldset: "introSection",
    }),
    defineField({
      name: "image",
      title: "Card Image",
      type: "image",
      options: { hotspot: true },
      group: "overview",
    }),
    defineField({
      name: "heroImages",
      title: "Hero Images",
      type: "array",
      of: [{ type: "image", options: { hotspot: true } }],
      description: "Rotating hero background images. First image is shown initially.",
      group: "overview",
    }),
    defineField({
      name: "heroTitle",
      title: "Hero Title",
      type: "string",
      description:
        'Override the hero headline. Defaults to "Rapture Surf Camp {name}". Use \\n for line breaks.',
      group: "overview",
    }),
    defineField({
      name: "heroSubtitle",
      title: "Hero Subtitle",
      type: "string",
      description: "Optional text below the hero headline.",
      group: "overview",
    }),
    defineField({
      name: "heroTagline",
      title: "Hero Tagline",
      type: "string",
      description: "Optional small uppercase text above the hero headline.",
      group: "overview",
    }),
    defineField({
      name: "rating",
      title: "Rating",
      type: "number",
      validation: (r) => r.min(0).max(5).precision(1),
      group: "overview",
    }),
    defineField({
      name: "reviewCount",
      title: "Review Count",
      type: "number",
      group: "overview",
    }),
    defineField({
      name: "amenities",
      title: "Amenities",
      type: "array",
      of: [{ type: "string" }],
      options: { layout: "tags" },
      group: "overview",
    }),
    defineField({
      name: "bookingUrl",
      title: "Booking URL",
      type: "url",
      group: "overview",
    }),
    defineField({
      name: "latitude",
      title: "Latitude",
      type: "number",
      group: "overview",
    }),
    defineField({
      name: "longitude",
      title: "Longitude",
      type: "number",
      group: "overview",
    }),
    defineField({
      name: "elfsightId",
      title: "Elfsight App ID",
      type: "string",
      description: "Elfsight reviews widget App ID",
      group: "overview",
    }),
    defineField({
      name: "pageBuilder",
      title: "Overview Page Content",
      type: "array",
      of: [
        { type: "contentBlock" },
        { type: "contentBlockGrid" },
        { type: "contentBlockVideo" },
        { type: "contentBlockImageCarousel" },
        { type: "imageGrid" },
        { type: "imageBreak" },
        { type: "imageCarousel" },
        { type: "imageGallery" },
        { type: "videoBlock" },
        { type: "videoTestimonials" },
        { type: "highlightsGrid" },
        { type: "inclusionsGrid" },
        { type: "surfSeasons" },
        { type: "climateInfo" },
        { type: "featureBlock" },
        { type: "elfsightReviews" },
        { type: "campSubPages" },
        { type: "faqSection" },
        { type: "ctaSection" },
      ],
      group: "overview",
    }),
    defineField({
      name: "seo",
      title: "SEO",
      type: "seo",
      group: "seo",
    }),
  ],
  preview: {
    select: {
      title: "name",
      subtitle: "country.name",
      media: "image",
    },
  },
});
